source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '9.0'

target 'Unity-iPhone' do
pod 'AdColony', '~> 3.3.4'
pod 'AppLovinSDK', '~> 5.0.1'
pod 'Geniee-iOS-SDK'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'MaioSDK', '~> 1.3.0'
pod 'NendSDK_iOS', '~> 4.0.6'
pod 'TapjoySDK', '~> 11.12.2'
pod 'UnityAds', '~> 2.2.1'
pod 'VungleSDK-iOS', '~> 6.2.0'
end
